djangoPrac/content/urls.py
from django.urls import path
from .views import Main, Modify, Post, delete, isGood, test  # views.py에서 import함

app_name='content'

urlpatterns=[
    path('main/', Main.as_view(),name='main'),
    path('main/post/', Post.as_view(),name='post'),
    path('main/post/<int:pk>', Modify.as_view(), name='modify'),   # pk로 변수이름 지정, views.py에서 받아옴
    path('main/delete/<int:pk>', delete, name='delete'),
    path('main/isGood/<int:pk>', isGood, name='isGood'),
    path('main/test', test, name='test'),
]

djangoPrac/djangoPrac/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('content.urls')),
]

djangoPrac/content/models.py
from django.db import models

# Create your models here.
class Feed(models.Model):
    content = models.TextField()   # 텍스트로 된 속성
    image = models.TextField()
    profile = models.TextField()
    nickname = models.TextField()
    like_count = models.IntegerField(default=0)   # 데이터베이스에 저장될 때 기본값을 0으로 함
    created_at = models.DateTimeField(auto_now_add=True)   # auto_now_add는 생성한 첫 시간을 Asia/Seoul 기준으로 넣음
    updated_at = models.DateTimeField(auto_now=True)   # auto_now는 수정해서 바뀐 시간을 넣어줌

    def __str__(self):   # 주석처리하면 첫번째 게시글이 아니라 Feed object라고 터미널에 뜸
        return self.content  # 보기 좋게 하는 용도
    
    def content_length(self):
        return len(self.content)
    content_length.short_description = '글자수'

djangoPrac/user/models.py
from django.db import models

# Create your models here.

djangoPrac/content/views.py
from django.shortcuts import redirect, render, resolve_url
from rest_framework.views import APIView
from .models import Feed
from django.db.models import Count, Avg
# Create your views here.

class Main(APIView):  
    def get(self, request):  # overriding
        feed_list = Feed.objects.all()  # 모든 정보 가져와서 저장

        for feed in feed_list:
            print(feed)  # terminal에서 오류 확인가능

        return render(request, "content/main.html", {   # 화면에 띄울 주소
            'feed_list': feed_list,  # main.html에 넘겨줄 요소
        })
    
    
class Post(APIView):
    def get(self, request):
        return render(request, "content/post.html")  # 요청받으면 띄움
    
    def post(self, request):
        content=request.POST.get('content')  # 정보를 가져옴, 위의 def get과 다름
        nickname=request.POST.get('nickname')
        image=request.POST.get('image')
        profile=request.POST.get('profile')

        feed = Feed()  # 데이터베이스에 가져온 정보를 저장
        feed.content = content
        feed.nickname = nickname
        feed.image = image
        feed.profile = profile
        feed.save()  # 데이터베이스에 갱신

        return redirect('content:main')  # 편의성을 위해 사용, 저장 후 다시 main 페이지로 돌아감
    # content 앱의 main 페이지로 감
class Modify(APIView):
    def post(self, request, pk):
        content=request.POST.get('content')  
        nickname=request.POST.get('nickname')
        image=request.POST.get('image')
        profile=request.POST.get('profile')

        feed = Feed.objects.get(id=pk)  # feed에서 해당 id에 해당하는 데이터 가져옴
        feed.content = content
        feed.nickname = nickname
        feed.image = image
        feed.profile = profile
        feed.save() 

        return redirect('content:main')

    def get(self, request, pk):
        feed = Feed.objects.get(id=pk)   # id가 pk와 같은 데이터 하나만 가져옴, cf) filter는 데이터 여러개 가져옴(중복 허용), get은 데이터 하나만 가져옴
        # = SELECT * FROM Feed WHERE id=pk
        return render(request, "content/modify.html", {
            'feed': feed,   # 'feed'라는 이름으로 feed 정보를 넘겨줌(사실상 json과 유사)
        })
    
def delete(request, pk):   # class로 해도 가능, POST로 밖에 하지 않아서 함수로 하는 것이 편함
    if request.method == 'POST':
        feed = Feed.objects.get(id=pk)
        feed.delete()
    return redirect('content:main')

def isGood(request, pk):
    if request.method == 'POST':
        s = request.POST.get('isGood')   # post방식으로 form안에 있는 button의 value 받아옴
        feed = Feed.objects.get(id=pk)
        if s == '좋아요':
            feed.like_count = feed.like_count+1
            print('좋아요')
        elif s == '싫어요' and feed.like_count>0:
            feed.like_count = feed.like_count-1
            print('싫어요')
        feed.save()
    # 좋아요 누르면 페이지가 제일 위로 가는 현상 막음, 해당 게시글이 위로가도록 함
    return redirect('{}#feed_{}'.format(   # format 뒤의 인자 2개가 중괄호 안에 순서대로 들어감
        resolve_url('content:main'), feed.id   # id일때는 #, class는 .을 줌
    ))

def test(request):
    if request.method == 'POST':
        #feed_list = Feed.objects.all()
        feed_list = Feed.objects.filter(like_count__range=(1,4))   # 좋아요가 1~4개인 게시글 가져옴
        #feed_list = Feed.objects.filter(like_count__gte=4, like_count__lt=8)  # 좋아요 수가 4이상 8미만인 게시글 가져옴
        #result = Feed.objects.aggregate(result = Count('id'))   # result = Count('id')의 result는 집계속성 이름 재지정해준 것
        result = Feed.objects.aggregate(result = Avg('like_count'))   # 모든 게시글의 좋아요 수 평균을 출력함
        return render(request, "content/main.html", {
            'feed_list':feed_list,
            'r':result,
        })

djangoPrac/user/views.py
from django.shortcuts import render

# Create your views here.

djangoPrac/content/templates/content/main.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>메인화면</title>
    </head>
    <body>
        <form action="{% url 'content:test' %}" method="post">
            {% csrf_token %}
            <button type="submit">테스트</button>
        </form>
        <div>
            <strong>테스트 결과: {{r.result}}</strong>
            <!--views.py의 def test의 r 테이블의 result 속성을 가져옴-->
        </div>
        {% for feed in feed_list %}
        <!--자바스크립트 문법(for문) 중괄호 퍼센트 사용-->
        <div>
            <a id="feed_{{ feed.id }}"></a>
            <!--책갈피 같은 개념-->
            <p>{{feed.content}}</p>
            <!--views.py로 넘겨온 정보들은 중괄호 2개 사용해야 인식함-->
            <p>{{feed.nickname}}</p>
            <img src="{{feed.image}}" />
            <p>{{feed.like_count}}</p>
            <form action="{% url 'content:isGood' feed.id %}" method="post">
                {% csrf_token %}
                <button type="submit" name="isGood" value="좋아요">좋아요</button>
                <button type="submit" name="isGood" value="싫어요">싫어요</button>
            </form>
            <p>생성된 날짜: {{feed.created_at}}</p>
            <p>수정된 날짜: {{feed.updated_at}}</p>
            <form action="{% url 'content:modify' feed.id %}" method="get">
                <button type="submit">수정</button>
            </form>
            <form action="{% url 'content:delete' feed.id %}" method="post">
                {% csrf_token %}
                <button type="submit">삭제</button>
            </form>
        </div>
        <hr />
        {% endfor %}
        <!--for문 닫음-->
    </body>
    <a href="{% url 'content:post' %}">글쓰기</a>
    <!--a 태그는 get방식으로 감-->
    <!--url 사용, content는 앱이름, post는 path이름(urls.py에서 설정)-->
</html>

djangoPrac/content/templates/content/modify.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>수정 페이지</title>
    </head>
    <body>
        <form method="post" action="{% url 'content:modify' feed.id %}">
            {% csrf_token %} content
            <!--접근 허용하기 위한 보안(접속한 사람의 토큰 대조, 토큰은 접속할 때마다 랜덤으로 생성됨)-->
            <input name="content" type="text" value="{{feed.content}}" />
            nickname
            <input name="nickname" type="text" value="{{feed.nickname}}" />
            imageURL
            <input name="image" type="text" value="{{feed.image}}" />
            profileURL
            <input name="profile" type="text" value="{{feed.profile}}" />
            <input type="submit" value="확인" />
        </form>
    </body>
</html>

djangoPrac/content/templates/content/post.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>글쓰기 페이지</title>
    </head>
    <body>
        <form id="makefeed" name="makefeed" method="post" action="{% url 'content:post' %}">
            <!--method가 get이었으면 데이터베이스에 저장이 되지 않음-->
            {% csrf_token %} content
            <input name="content" type="text" />
            <!--value가 없어서 빈칸으로 나옴-->
            nickname
            <input name="nickname" type="text" />
            imageURL
            <input name="image" type="text" />
            profileURL
            <input name="profile" type="text" />
            <input type="submit" value="확인" />
        </form>
        <!--백엔드로 통신보냄-->
    </body>
</html>